---
title: "Naming convention"
author: "Joe Shaw"
format: pdf
editor: visual
---

I have developed a naming convention for this project to (hopefully) make the process of organising the data clearer.

# Definitions

## **Genetic tests**

-   **glvar:** germ-line variant data.
    Data generated by next generation sequencing for analysis of germline (i.e inherited) sequence variants.
    This refers to test directory indication R207 for inherited ovarian cancer.

-   **tvar:** tumour variant data.
    Data generated by next generation sequencing of DNA from formalin-fixed paraffin-embedded (FFPE) tumour tissue for analysis of somatic sequence variants.
    This may be referred to as "tumour BRCA" or "tBRCA", but I have chosen "tvar" as variants in non-BRCA genes may also be detected.

-   **gi:** genomic instability results.
    Results for assessment of genomic instability, such as using shallow whole genome sequencing with the SeqOne SomaHRD pipeline.

## **Data sources**

-   **dnadb:** data from the DNA Database, also referred to as DLIMS.

-   **igene:** data from the iGene database.

-   **csv:** data from csv files downloaded from the SeqOne website

## **Identifiers**

-   **labno:** the laboratory number or "DNA number" used on DNA Database.
    Any labno is an 8-digit string of numbers.
    The first two digits indicate the year the sample was received.

-   **rno:** the iGene referral (R) number.

-   **nhsno:** the patient's 10 digit NHS number.

-   **pathno:** the identifier of the FFPE pathology block from which DNA was extracted.
    Different pathology labs have different formats for pathno.

-   **ws:** the worksheet the sample was tested on at the Manchester Genomic Laboratory Hub.
    The format is WS followed by 6 digits.

## **Verbs**

-   **annotate:** add on useful information.

-   **bind:** bind together two (or more) large datasets, using the rbind function.

-   **clean:** filtering a table, removing duplicates or tidying up free-text columns.

-   **collate:** bring together many different smaller files.

-   **extract:** pull information out of a database.

-   **join:** bring two tables together using a common key variable

## Projects

-   **service:** samples tested as part of the live clinical service, with a genetic result returned to a clinician.

-   **validation:** samples tested as part of a validation of a method, with no genetic result returned to a clinician.

## **Acronyms**

-   **orpp:** One Result Per Patient

-   **orps:** One Result Per Sample

-   **ICP:** Inherited Cancer Panel

# File naming

The naming convention for files and tables is: genetic test, then data source, then what has been done to the data.

Example: "tvar_dnadb_cleaned" - tumour variant data sourced from DNA Database which has been cleaned.
